# Generated by Django 4.0.1 on 2022-01-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarImage',
            fields=[
                ('user_name', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('avatar_path', models.CharField(max_length=1024)),
            ],
        ),
    ]
