# Generated by Django 4.0.1 on 2022-04-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvatarImage',
        ),
    ]
